### PR TITLE
LPS-57333 Use ddmField.getDefaultLocale instead

### PR DESCRIPTION
**Pull request by marcellustavares**
@cleydyr, could you write tests for this?

This is a high priority ticket and we should merge only with tests to avoid any future regressions.

Thanks

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @cleydyr,

What's the status of this pull? Did you make any progress on this?

**Comment by juangon** [comment]
Hi mates, Shouldn't be this fixed by this fix? https://github.com/dustinryerson/liferay-portal-ee/pull/1453

**Comment by marcellustavares** [comment]
hey @cleydyr, could you check @juangon changes, should we apply to master?

Thanks

**Comment by juangon** [comment]
Oh great having notifications. After discussing with @juliocamarero (https://github.com/ZoltanTakacs/liferay-portal-ee/pull/982) we thing that this commit https://github.com/dustinryerson/liferay-portal-ee/commit/2335b17526be7b10718fba62be79268be6f6b03f isn't needed, and we only should check the field for default language, not all the locales. So, the next commit (https://github.com/dustinryerson/liferay-portal-ee/commit/414ea1f7fff8ca156c5df7a7bfe74520a1f07d71) wouldn't be necessary. I am not sure now if this still applies to your case @cleydyr

**Comment by juangon** [comment]
Hmm I think you case could be fixed using the second commit of my pull (https://github.com/dustinryerson/liferay-portal-ee/commit/414ea1f7fff8ca156c5df7a7bfe74520a1f07d71) using the defaultLocale parameter and checking if it's required or not, BUT removing the locales iteration, and just use the defaultLocale instead.

**Comment by cleydyr** [comment]
Closing as LPS-57333 has got another solution.

**Pull request closed without merging**
