### PR TITLE
LPS-69227

### PR DESCRIPTION
**Pull request by danielkocsis**
Hey @cleydyr,

I made some changes on your pull, could you please verify these? If it looks good just let me know and I'll forward it.

Daniel

### CODE REVIEW

**Comment by cleydyr** [comment]
Hello, @danielkocsis.

I think https://github.com/cleydyr/liferay-portal/pull/22/commits/c31ab64745b3e388bb7f24b22c825aef7d8dad7c is more simple and elegant than my previous idea, as it takes advantage of the information contained on `LocaleThreadLocal`. Actually the `for` loop would be unnecessary as `nameMap.entrySet() ` will have only non-null values.

It looks great for me. You can forward it.

Thank you very much.

**Comment by cleydyr** [comment]
Forwarded as https://github.com/brianchandotcom/liferay-portal/pull/46016. Closing now.

**Comment by danielkocsis** [comment]
Hey @cleydyr,

please see Brian's comment: https://github.com/brianchandotcom/liferay-portal/pull/46016#issuecomment-271021004

Could you please take care of this and resend to me?

thanks,
Daniel

**Comment by cleydyr** [comment]
Sure thing, @danielkocsis. I'll take care of it.

Thanks.

**Comment by cleydyr** [comment]
I've sent you https://github.com/danielkocsis/liferay-portal/pull/595.

**Pull request closed without merging**
